version: '3'
services:
    gitlab:
        image: gitlab/gitlab-ce:11.8.10-ce.0
        restart: always
        container_name: gitlab
        volumes:
            - ./srv/gitlab/config:/etc/gitlab:z
            - ./srv/gitlab/logs:/var/log/gitlab:z
            - ./srv/gitlab/data:/var/opt/gitlab:z
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://192.168.33.20:10080/'
                gitlab_rails['gitlab_shell_ssh_port'] = 10022
        ports:
            - "10080:10080"
            - "10022:22"
        networks:
            gitlab_net:
                ipv4_address: 172.16.238.2
    gitlab-runner:
        image: gitlab/gitlab-runner:v11.8.0
        restart: always
        container_name: gitlab-runner
        volumes:
            - ./srv/gitlab-runner/config:/etc/gitlab-runner:z
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - gitlab
        extra_hosts:
            - "192.168.33.20:172.16.238.2"
        networks:
            gitlab_net:
                ipv4_address: 172.16.238.3

networks:
    gitlab_net:
        ipam:
            config:
            - subnet: 172.16.238.0/24
