concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "332719fc4296"
  url = "http://172.16.238.2:10080"
  token = "NiD8J9smsDHj5sQ2AZpP"
  executor = "docker"
  clone_url = "http://172.16.238.2:10080"
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mode = "gitlab_gitlab_net"
    pull_policy = "if-not-present"
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
