concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "c921e93d7700"
  url = "http://172.16.238.2:10080"
  token = "sW2kTnxzrRnUNysyx63K"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
