concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "c921e93d7700"
  url = "http://172.16.238.2:10080"
  token = "sW2kTnxzrRnUNysyx63K"
  executor = "docker"
  clone_url = "http://172.16.238.2:10080"
  [runners.docker]
    memory_limit = 3GB
    tls_verify = false
    image = "docker:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache","/var/run/docker.sock:/var/run/docker.sock:rw"]
    shm_size = 0
    network_mode = "gitlab_gitlab_net"
    pull_policy = "if-not-present"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
